apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: wp-ingress
  namespace: default
spec:
  rules:
  - host: test.class
    http:
      paths:
      - path: /redmine
        backend:
          serviceName: redmine-svc
          servicePort: 3000
      - path: /
        backend:
          serviceName: wp-svc
          servicePort: 80
