apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-db
  labels:
    appdb: wp-db
spec:
  replicas: 1
  serviceName: wp-db
  selector:
    matchLabels:
      appdb: wp-db
  template:
    metadata:
      labels:
        appdb: wp-db
    spec:
      volumes:
      - name: wp-pv-storage
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wp-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: wp-db-cm
        volumeMounts:
        - name: wp-pv-storage
          mountPath: "/var/lib/mysql"
          