apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-db
  labels:
    appdb: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: wp-db
  template:
    metadata:
      labels:
        appdb: wp-db
    spec:
      containers:
      - name: wp-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: wp-db-cm