apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app
  labels:
    app: wpp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp-app
        image: wordpress:latest
        ports:
        - containerPort: 8080
          name: web-port
        envFrom:
        - configMapRef:
            name: wp-app-cm